import React, { useState } from 'react';
import { Eye, EyeOff, Check, X, Lock } from 'lucide-react';

export const PasswordSetup = ({
  role = 'student',
  verifiedEmail = '',
  usernameOption = 'email', // 'email', 'autogen', 'custom'
  onChangeUsernameOption,
  customUsername = '',
  onChangeCustomUsername,
  password = '',
  onChangePassword,
  confirmPassword = '',
  onChangeConfirmPassword,
  autoUsername = ''
}) => {
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  // Live password rules validation
  const rules = [
    { label: 'Minimum 13 characters', isValid: password.length >= 13 },
    { label: 'At least one uppercase letter (A-Z)', isValid: /[A-Z]/.test(password) },
    { label: 'At least one lowercase letter (a-z)', isValid: /[a-z]/.test(password) },
    { label: 'At least one numeric digit (0-9)', isValid: /[0-9]/.test(password) },
    { label: 'At least one special character (!@#$%^&*)', isValid: /[^A-Za-z0-9]/.test(password) }
  ];

  const validCount = rules.filter(r => r.isValid).length;
  const strengthPercentage = (validCount / rules.length) * 100;

  const getStrengthLabel = () => {
    if (validCount <= 1) return { label: 'Weak', color: 'var(--color-error)' };
    if (validCount <= 3) return { label: 'Medium', color: 'var(--color-accent-yellow)' };
    if (validCount === 4) return { label: 'Good', color: '#319795' };
    return { label: 'Strong', color: 'var(--color-primary-green)' };
  };

  const strengthInfo = getStrengthLabel();

  return (
    <div className="slide-up" style={{ textAlign: 'left' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '20px' }}>
        <Lock size={20} color="var(--color-primary-purple)" />
        <h4 style={{ fontSize: '17px', fontWeight: 700, color: 'var(--color-dark-text)', margin: 0 }}>
          Create Security Credentials
        </h4>
      </div>

      {/* Username Setup for Career Explorer */}
      {role === 'student' ? (
        <div className="form-group" style={{ marginBottom: '24px', background: '#f8fafc', padding: '16px', borderRadius: '12px', border: '1px solid var(--color-border-light)' }}>
          <label className="form-label">Username Selection</label>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '8px' }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', fontSize: '14px' }}>
              <input
                type="radio"
                name="usernameChoice"
                value="email"
                checked={usernameOption === 'email'}
                onChange={() => onChangeUsernameOption('email')}
              />
              <span>Use verified email (<strong>{verifiedEmail || 'email@example.com'}</strong>)</span>
            </label>
            <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', fontSize: '14px' }}>
              <input
                type="radio"
                name="usernameChoice"
                value="autogen"
                checked={usernameOption === 'autogen'}
                onChange={() => onChangeUsernameOption('autogen')}
              />
              <span>Use autogenerated ID (<strong>{autoUsername || 'ANT-2026-X89'}</strong>)</span>
            </label>
          </div>
        </div>
      ) : (
        <div className="form-group" style={{ marginBottom: '20px' }}>
          <label className="form-label">Username</label>
          <input
            type="text"
            className="form-input"
            value={verifiedEmail}
            disabled
            style={{ backgroundColor: '#f1f5f9', opacity: 0.8 }}
          />
          <span style={{ fontSize: '12px', color: 'var(--color-text-subtle)', marginTop: '4px', display: 'block' }}>
            Your verified email address is automatically set as your system username.
          </span>
        </div>
      )}

      {/* Password Field */}
      <div className="form-group">
        <label className="form-label">Create Password <span style={{ color: 'var(--color-error)' }}>*</span></label>
        <div style={{ position: 'relative' }}>
          <input
            type={showPassword ? 'text' : 'password'}
            className="form-input"
            value={password}
            onChange={e => onChangePassword(e.target.value)}
            placeholder="Enter a strong password (min 13 characters)..."
            style={{ paddingRight: '48px' }}
          />
          <button
            type="button"
            onClick={() => setShowPassword(!showPassword)}
            style={{
              position: 'absolute',
              right: '12px',
              top: '50%',
              transform: 'translateY(-50%)',
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              color: 'var(--color-text-muted)'
            }}
          >
            {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
          </button>
        </div>
      </div>

      {/* Password Strength Indicator Bar */}
      {password && (
        <div style={{ marginBottom: '16px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '6px' }}>
            <span style={{ color: 'var(--color-text-muted)' }}>Password Strength:</span>
            <strong style={{ color: strengthInfo.color }}>{strengthInfo.label}</strong>
          </div>
          <div style={{ width: '100%', height: '6px', backgroundColor: 'var(--color-border-light)', borderRadius: '9999px', overflow: 'hidden' }}>
            <div style={{ width: `${strengthPercentage}%`, height: '100%', backgroundColor: strengthInfo.color, transition: 'all 0.3s' }}></div>
          </div>
        </div>
      )}

      {/* Live Password Rules Checklist */}
      <div style={{ background: '#ffffff', border: '1px solid var(--color-border-light)', borderRadius: '12px', padding: '14px', marginBottom: '20px' }}>
        <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--color-text-muted)', display: 'block', marginBottom: '8px', textTransform: 'uppercase' }}>
          Password Policy Requirements
        </span>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '6px' }}>
          {rules.map((rule, idx) => (
            <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: rule.isValid ? 'var(--color-primary-green)' : 'var(--color-text-muted)' }}>
              {rule.isValid ? <Check size={14} color="var(--color-primary-green)" /> : <X size={14} color="var(--color-text-subtle)" />}
              <span>{rule.label}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Confirm Password Field */}
      <div className="form-group">
        <label className="form-label">Confirm Password <span style={{ color: 'var(--color-error)' }}>*</span></label>
        <div style={{ position: 'relative' }}>
          <input
            type={showConfirmPassword ? 'text' : 'password'}
            className="form-input"
            value={confirmPassword}
            onChange={e => onChangeConfirmPassword(e.target.value)}
            placeholder="Re-enter password to verify..."
            style={{ paddingRight: '48px' }}
          />
          <button
            type="button"
            onClick={() => setShowConfirmPassword(!showConfirmPassword)}
            style={{
              position: 'absolute',
              right: '12px',
              top: '50%',
              transform: 'translateY(-50%)',
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              color: 'var(--color-text-muted)'
            }}
          >
            {showConfirmPassword ? <EyeOff size={18} /> : <Eye size={18} />}
          </button>
        </div>
        {confirmPassword && password !== confirmPassword && (
          <span style={{ color: 'var(--color-error)', fontSize: '12px', marginTop: '4px', display: 'block' }}>
            Passwords do not match.
          </span>
        )}
      </div>
    </div>
  );
};
